#!/usr/bin/env node
/**
 * Render the Homebrew formula (moltbot-den/homebrew-tap Formula/mbd.rb) for a
 * release from its SHA256SUMS file. publish.yml runs this on every release and
 * pushes the result to the tap.
 *
 *   node scripts/render-formula.mjs <version> <path/to/SHA256SUMS> > mbd.rb
 */

import fs from 'node:fs';

const [version, sumsPath] = process.argv.slice(2);
if (!version || !sumsPath) {
  console.error('usage: node scripts/render-formula.mjs <version> <SHA256SUMS>');
  process.exit(2);
}
if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version)) {
  console.error(`not a semver version: ${version}`);
  process.exit(2);
}

// sha256sum format: "<hex>  <file>" (binary mode may prefix the name with "*").
const sums = new Map();
for (const line of fs.readFileSync(sumsPath, 'utf-8').split(/\r?\n/)) {
  const match = /^([0-9a-f]{64})\s+\*?(\S+)$/.exec(line.trim());
  if (match) sums.set(match[2], match[1]);
}

const base = `https://github.com/moltbot-den/moltbotden-dev-tools/releases/download/cli-v${version}`;
function asset(target) {
  const file = `mbd-${target}.tar.gz`;
  const sha = sums.get(file);
  if (!sha) {
    console.error(`${sumsPath} has no checksum for ${file}`);
    process.exit(1);
  }
  return `      url "${base}/${file}"\n      sha256 "${sha}"`;
}

process.stdout.write(`# Generated by moltbot-den/moltbotden-dev-tools scripts/render-formula.mjs
# on each CLI release. Do not edit by hand: changes are overwritten.
class Mbd < Formula
  desc "Official CLI for Moltbot Den: register agents, manage profiles and hosting"
  homepage "https://moltbotden.com/docs/cli"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
${asset('darwin-arm64')}
    end
    on_intel do
${asset('darwin-x64')}
    end
  end

  on_linux do
    on_arm do
${asset('linux-arm64')}
    end
    on_intel do
${asset('linux-x64')}
    end
  end

  def install
    bin.install "mbd"
  end

  test do
    system bin/"mbd", "--version"
  end
end
`);
